### ISSUE TITLE
Navigator is Incompatible when work with Epoxy...

### ISSUE THREAD

**Issue by JasonHezz** [shaishavgandhi05/navigator#121]
kotlin compiler shows

NoSuchMethodError : com.square.kotlin poet.Annotation.getType

Maybe it’s KotlinPoet version issue. Epoxy is 1.0.1 , Navigator is 1.0.0. Hopefully this can be solved.

**Comment by shaishavgandhi05** [comment]
Hi, thanks for reporting this. I've updated the KotlinPoet version but haven't yet released it. You can however use the `1.0.0-SNAPSHOT`. I'm close to releasing 1.0.0 so it should be soon. 

If you haven't used a snapshot, here's how to configure it:

In your root `build.gradle` project:
```groovy
allprojects {
    repositories {
        // Your other repos
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
    }
}
```

Then you can simply use `com.shaishavgandhi.navigator:navigator:1.0.0-SNAPSHOT`

**Comment by JasonHezz** [comment]
Not working...
New exception NoSuchElementException: List is empty occurs

**Comment by shaishavgandhi05** [comment]
I saw that error while updating to KotlinPoet 1.1.0. Seems like a bug on KotlinPoet side. I've submitted a fix here https://github.com/square/kotlinpoet/pull/644

Can you paste the full stacktrace so that it's possible for me to verify that it is the same bug?

**Comment by JasonHezz** [comment]
![Image](https://i.imgur.com/WiNsuCj.jpg)

**Comment by JasonHezz** [comment]
I can’t send any message from company because of private policy , but I’m sure it’s the same log when I compile failed.

**Comment by shaishavgandhi05** [comment]
Yup, looks the same. I'll upload a new SNAPSHOT soon after verifying the fix worked.

**Comment by shaishavgandhi05** [comment]
I've uploaded a new SNAPSHOT with the fix. Please try again and let me know if it works (be sure to clear cache otherwise it will depend on the older snapshot)

**Comment by JasonHezz** [comment]
Great ! Thanks , waiting for 1.0.0 version .

**Comment by shaishavgandhi05** [comment]
Thanks! I'll try and release an RC this weekend.
