### ISSUE TITLE
Logo Proposal: Navigator

### ISSUE THREAD

**Issue by baranpirincal** [shaishavgandhi05/navigator#73]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Baran Pirinçal

Graphic Designer

**Comment by shaishavgandhi05** [comment]
That sounds great. Would love to set a logo that goes with the concept!

**Comment by baranpirincal** [comment]
Do you have an any idea or suggestion about design decisions? Feel free to share with me 
It would be better!

**Comment by shaishavgandhi05** [comment]
I'm not a very design-oriented person. Most probably my suggestions will be a hindrance. So go for it as you see fit 😄

**Comment by baranpirincal** [comment]
@shaishavgandhi05 

Hey again,

I want to get comments from you :)

Best Regards
Baran Pirinçal

![navigator](https://user-images.githubusercontent.com/37786733/42403522-7938155c-818a-11e8-96af-0ceddfa5a2de.jpg)

**Comment by shaishavgandhi05** [comment]
Hey! This looks great. Can we skip the tag line "annotation processor that eliminates navigation boilerplate"?

Also, not sure if the pile of books are a good representation of what the library stands for. Might be interesting to have something that indicates navigation in terms of screens.

**Comment by baranpirincal** [comment]
Hey, thank you!

I am little bit confused about function of the project because of that I am not sure how can I show navigation on it.  I am sorry but I did not imagine that. I would be happy if you explain more your navigation and screen idea. Anything can be okay for me like reference graphics , information text or logo design examples.

Best Regards
Baran Pirinçal

**Comment by shaishavgandhi05** [comment]
Sure. The project is basically used to help developers write code that will take the user from one screen to another. 
For example, when you're using a mobile app, let's say a news app, you have a screen which has the list of headlines. You then click on one of them and it takes you to a screen which has the entire article. That flow looks something like
```
ListScreen -> DetailScreen
```

This library helps with writing code that will take the user from one screen to another like the example mentioned above. 

Considering that, it might be useful to incorporate the idea of moving from one screen to another into the logo. I don't have a visual representation sadly. Hope this helps. Also, I appreciate the help!

**Comment by baranpirincal** [comment]
@shaishavgandhi05 

Hey, it is not finished.

I'm not sure... I just want to get comments from you.

Also we can add text below the icons

![navigoatrsonson](https://user-images.githubusercontent.com/37786733/42573430-c19ba56e-8524-11e8-8067-5e36fea36f29.jpg)

**Comment by shaishavgandhi05** [comment]
I like the idea of just adding the test below the icon. I like the second icon. Maybe we can do the icon and just plain text of "navigator" below it?

**Comment by shaishavgandhi05** [comment]
Liked the one on the right 😄

**Comment by baranpirincal** [comment]
![navigatorcoverpage](https://user-images.githubusercontent.com/37786733/42656339-a8940f94-8627-11e8-8b70-7854ac6b1cfd.jpg)

**Comment by baranpirincal** [comment]
Hey again @shaishavgandhi05 

I uploaded all variations of logo design and created pull-request.

Good luck with that! 

Best Regards
Baran Pirinçal

**Comment by shaishavgandhi05** [comment]
Have added the logo to the Readme.md. Thanks for the contribution!
